// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Api.Data;

#nullable disable

namespace Movie.Api.Migrations
{
    [DbContext(typeof(MovieStoreContext))]
    partial class MovieStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movie.Api.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Director");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1946, 12, 18),
                            Name = "Steven Spielberg",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1970, 7, 30),
                            Name = "Christopher Nolan",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1963, 3, 27),
                            Name = "Quentin Tarantino",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1942, 11, 17),
                            Name = "Martin Scorsese",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(1937, 11, 30),
                            Name = "Ridley Scott",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(1941, 1, 5),
                            Name = "Hayao Miyazaki",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(1971, 5, 14),
                            Name = "Sofia Coppola",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(1964, 10, 9),
                            Name = "Guillermo del Toro",
                            Nationality = "Mexican"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateOnly(1949, 9, 25),
                            Name = "Pedro Almodóvar",
                            Nationality = "Spanish"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateOnly(1983, 8, 4),
                            Name = "Greta Gerwig",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("Movie.Api.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Movie.Api.Entities.Movie", b =>
                {
                    b.HasOne("Movie.Api.Entities.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });
#pragma warning restore 612, 618
        }
    }
}
